name: mastering-ci-cd 

on: [push]


jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 

    - name: echo the hello world 
      run: echo "hello-world"
    
    - name: getting github event name 
      run: echo "this job is run on the github event name: ${{ github.event_name }}"

name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."