name: mastering-ci-cd 

on: 
  push: 
    branches: ["main"]


jobs: 
  first-job: 
    runs-on: 
    strategy: 
       matrix: 
        os: [ubuntu-linux]


    steps: 
    - uses: actions/checkout@v3 

    - name: echo the hello world 
      run: echo hello-world