name: mastering-ci-cd 
description: this is used to learn the github ci/cd properly for my knowledge. 
on: [push]


jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 

    - name: echo the hello world 
      run: echo "hello-world"


